logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: WARN

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    
server:
  port: 8080
proxy:
  auth:
    routes:
      customers: oauth2
      stores: passthru
      recommendations: none  
spring:
  aop:
    proxy-target-class: true
  application:
    name: service-zuul-gateway
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  messages:
    basename: message

#zuul 匹配的规则有先后关系
zuul:
#  add-host-header: true
#  uul.addProxyHeaders: false
  routes:
    ui1:
      path: /ui1/**
      service-id: service-ui1
      #url: http://localhost:8081/ui1
#    startpage:
#      path: /**
#      #url: http://localhost:7777
#      serviceId: service-main
    resource:
      path: /resource/**
      url: http://localhost:9001/resource
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user
  ignored-services: "*"

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: ui1
      clientSecret: ui1-secret
    resource:
      userInfoUri: http://localhost:9999/uaa/user
      preferTokenInfo: false
      logout:
        url: http://localhost:9999/uaa/revoke-token
  sessions: ALWAYS
